### ISSUE TITLE
Pressed(button) behave as WaitForPressed(button)

### ISSUE THREAD

**Issue by michaelmera** [PistonDevelopers/ai_behavior#59]
Currently, the `Pressed(button)` behavior is: `Running` as long as the corresponding button is not pressed and then `Success` when pressed (similar behavior for `Released(button)`).

Is this the intended behavior? It leads to rather counter-intuitive constructs like:

``` rust
While(Pressed(Key::Left), vec![...])
```

This will run the content of the `While` as long as the Left key is NOT pressed.

If this is not intended, I am willing to create a pull request to fix this, but as I am not sure how the piston inputs works:
- Is there a chance that a key pressed event is skipped?
- Is there a chance that a key released event is skipped?
- can I avoid using events in this case and rather query the state of the particular key?

If this is intended, I am willing to create a pull request to change the names from Pressed/Released to WaitForPressed/WaitForReleased.

**Comment by bvssvni** [comment]
I agree. `WaitForPressed` is more intuitive.
