### ISSUE TITLE
Question: what is "The remaining delta time" dt?

### ISSUE THREAD

**Issue by Sollimann** [PistonDevelopers/ai_behavior#86]
@bvssvni Looking at the definition of `ActionArgs`, what do you mean by `dt` being "the remaining delta time". I thought the `dt` were the time elapsed since the last time you ticked/invoked/traversed the tree?

```rs
/// The action is still running.
pub const RUNNING: (Status, f64) = (Running, 0.0);

/// The arguments in the action callback.
pub struct ActionArgs<'a, E: 'a, A: 'a, S: 'a> {
    /// The event.
    pub event: &'a E,
    /// The remaining delta time.
    pub dt: f64,
    /// The action running.
    pub action: &'a A,
    /// The state of the running action, if any.
    pub state: &'a mut Option<S>,
}
```

Also, why does `RUNNING` return zero delta time?

Btw, great library you have here, keep up the good work with Piston! :mechanical_arm:

**Comment by Sollimann** [comment]
@Potpourri would you know? :)

**Comment by bvssvni** [comment]
When one action terminates, it can consume some of `dt` and the remaining is passed onto the next action.
